---
- name: add redis ppa apt repo
  apt_repository:
    repo: ppa:chris-lea/redis-server
    state: present

- name: intall redis
  apt:
    name: ["redis-server", "redis-tools"]

- name: remove default init.d file
  file:
    path: /etc/init.d/redis-server
    state: absent

- name: remove default config file
  file:
    path: /etc/redis/redis.conf
    state: absent

- name: disable default system service
  systemd:
    name: redis-server
    enabled: no
    state: stopped

- name: remove default systemd service file
  file:
    path: /lib/systemd/system/redis-server.service
    state: absent
...
