---
- include: check_vars.yml

- block:
    - include: download.yml
      tags:
        - download

    - include: dependencies.yml
      tags:
        - install

    - include: install.yml
      tags:
        - install
  when: ansible_os_family != "Debian" or not install_from_repo

- include: install-from-apt.yml
  tags:
    - install
  when:
    - ansible_os_family == "Debian"
    - install_from_repo


- include: server.yml
  when: redis_server
  tags:
    - config

- include: sentinel.yml
  when: redis_sentinel
  tags:
    - config

- include: local_facts.yml
  when: redis_local_facts|bool
